<?php

namespace Database\Seeders;

use App\Models\Medicine;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $medicines = [
            [
                'name' => 'Paracetamol',
                'generic_name' => 'Acetaminophen',
                'brand_name' => 'Tylenol',
                'description' => 'Pain reliever and fever reducer',
                'category' => 'Analgesics',
                'price' => 5.50,
                'stock_quantity' => 100,
                'manufacturer' => 'Johnson & Johnson',
                'requires_prescription' => false,
            ],
            [
                'name' => 'Amoxicillin',
                'generic_name' => 'Amoxicillin',
                'brand_name' => 'Amoxil',
                'description' => 'Antibiotic used to treat bacterial infections',
                'category' => 'Antibiotics',
                'price' => 12.75,
                'stock_quantity' => 80,
                'manufacturer' => 'GSK',
                'requires_prescription' => true,
            ],
            [
                'name' => 'Ibuprofen',
                'generic_name' => 'Ibuprofen',
                'brand_name' => 'Advil',
                'description' => 'Anti-inflammatory pain reliever',
                'category' => 'NSAIDs',
                'price' => 8.25,
                'stock_quantity' => 120,
                'manufacturer' => 'Pfizer',
                'requires_prescription' => false,
            ],
            [
                'name' => 'Metformin',
                'generic_name' => 'Metformin HCl',
                'brand_name' => 'Glucophage',
                'description' => 'Medication for type 2 diabetes',
                'category' => 'Antidiabetics',
                'price' => 15.30,
                'stock_quantity' => 60,
                'manufacturer' => 'Bristol Myers Squibb',
                'requires_prescription' => true,
            ],
            [
                'name' => 'Omeprazole',
                'generic_name' => 'Omeprazole',
                'brand_name' => 'Prilosec',
                'description' => 'Proton pump inhibitor for acid reflux',
                'category' => 'Gastrointestinal',
                'price' => 18.90,
                'stock_quantity' => 45,
                'manufacturer' => 'AstraZeneca',
                'requires_prescription' => true,
            ],
            [
                'name' => 'Aspirin',
                'generic_name' => 'Acetylsalicylic Acid',
                'brand_name' => 'Bayer',
                'description' => 'Pain reliever and blood thinner',
                'category' => 'Analgesics',
                'price' => 4.75,
                'stock_quantity' => 150,
                'manufacturer' => 'Bayer',
                'requires_prescription' => false,
            ],
            [
                'name' => 'Lisinopril',
                'generic_name' => 'Lisinopril',
                'brand_name' => 'Prinivil',
                'description' => 'ACE inhibitor for high blood pressure',
                'category' => 'Cardiovascular',
                'price' => 22.40,
                'stock_quantity' => 35,
                'manufacturer' => 'Merck',
                'requires_prescription' => true,
            ],
            [
                'name' => 'Cetirizine',
                'generic_name' => 'Cetirizine HCl',
                'brand_name' => 'Zyrtec',
                'description' => 'Antihistamine for allergies',
                'category' => 'Antihistamines',
                'price' => 9.85,
                'stock_quantity' => 90,
                'manufacturer' => 'UCB',
                'requires_prescription' => false,
            ],
            [
                'name' => 'Atorvastatin',
                'generic_name' => 'Atorvastatin Calcium',
                'brand_name' => 'Lipitor',
                'description' => 'Statin for cholesterol management',
                'category' => 'Cardiovascular',
                'price' => 28.60,
                'stock_quantity' => 25,
                'manufacturer' => 'Pfizer',
                'requires_prescription' => true,
            ],
            [
                'name' => 'Hydrochlorothiazide',
                'generic_name' => 'HCTZ',
                'brand_name' => 'Microzide',
                'description' => 'Diuretic for blood pressure and fluid retention',
                'category' => 'Diuretics',
                'price' => 11.20,
                'stock_quantity' => 70,
                'manufacturer' => 'Capsugel',
                'requires_prescription' => true,
            ],
            [
                'name' => 'Loratadine',
                'generic_name' => 'Loratadine',
                'brand_name' => 'Claritin',
                'description' => 'Non-drowsy antihistamine',
                'category' => 'Antihistamines',
                'price' => 7.95,
                'stock_quantity' => 110,
                'manufacturer' => 'Bayer',
                'requires_prescription' => false,
            ],
            [
                'name' => 'Prednisone',
                'generic_name' => 'Prednisone',
                'brand_name' => 'Deltasone',
                'description' => 'Corticosteroid for inflammation',
                'category' => 'Corticosteroids',
                'price' => 14.75,
                'stock_quantity' => 40,
                'manufacturer' => 'Pfizer',
                'requires_prescription' => true,
            ],
            [
                'name' => 'Simvastatin',
                'generic_name' => 'Simvastatin',
                'brand_name' => 'Zocor',
                'description' => 'Statin for cholesterol reduction',
                'category' => 'Cardiovascular',
                'price' => 19.85,
                'stock_quantity' => 55,
                'manufacturer' => 'Merck',
                'requires_prescription' => true,
            ],
            [
                'name' => 'Vitamin D3',
                'generic_name' => 'Cholecalciferol',
                'brand_name' => 'Nature Made',
                'description' => 'Vitamin D supplement',
                'category' => 'Vitamins',
                'price' => 12.30,
                'stock_quantity' => 200,
                'manufacturer' => 'Nature Made',
                'requires_prescription' => false,
            ],
            [
                'name' => 'Insulin Glargine',
                'generic_name' => 'Insulin Glargine',
                'brand_name' => 'Lantus',
                'description' => 'Long-acting insulin for diabetes',
                'category' => 'Antidiabetics',
                'price' => 95.50,
                'stock_quantity' => 15,
                'manufacturer' => 'Sanofi',
                'requires_prescription' => true,
            ],
        ];

        foreach ($medicines as $medicine) {
            Medicine::create(array_merge($medicine, [
                'expiry_date' => fake()->dateTimeBetween('now', '+3 years')->format('Y-m-d'),
            ]));
        }
    }
}
